# This is a basic workflow to help you get started with Actions

name: Create RG

on:
  workflow_call:
    inputs:
      environmentname:
        required: true
        type: string
      Az_RG_Name:
        required: true
        type: string
    
    secrets:
      AZURE_CREDENTIALS:
        
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environmentname}}
    steps:
      - uses: actions/checkout@v3
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Create RG
        uses: azure/cli@v1
        with:
          inlineScript: az group create --name ${{inputs.Az_RG_Name}} --location 'WestEurope'
  