# This is a basic workflow to help you get started with Actions

name: Deploy to environments

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/CreateRG.yml
        secrets: inherit
        with:
          environmentname: test
          Az_RG_Name: RG30-test
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-test]
    steps:
      - uses: ./.github/workflows/CreateRG.yml
        secrets: inherit
        with:
          environmentname: production
          Az_RG_Name: RG30-prod
          