# This is a basic workflow to help you get started with Actions

name: Deploy Azure Resources

on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/workflows/*","*.ps1"]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run Bicep linter test
        run: az bicep build --file storage.bicep

